import type { Meta, StoryObj } from '@storybook/react'
import { fn } from '@storybook/test'
import { List } from '../../components/lists/list/List'

const meta = {
  title: 'Example/Lists/List',
  component: List,
  parameters: {
    layout: 'centered',
  },
} satisfies Meta<typeof List>

export default meta
type Story = StoryObj<typeof meta>

export const FourOptionsList: Story = {
  args: {
    options: [
      {
        label: 'Option 1',
        value: 'OPTION_1',
        feature: null,
        position: 0,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 2',
        value: 'OPTION_2',
        feature: null,
        position: 1,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 3',
        value: 'OPTION_3',
        feature: null,
        position: 2,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 4',
        value: 'OPTION_4',
        feature: null,
        position: 3,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
    ],
  },
  argTypes: {
    direction: { control: false },
    selected: { control: false },
  },
}

export const FourOptionsListWithSeparator: Story = {
  args: {
    options: [
      {
        label: 'Group 1',
        value: null,
        feature: null,
        position: 0,
        type: 'TITLE',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 1',
        value: 'OPTION_1',
        feature: null,
        position: 1,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 2',
        value: 'OPTION_1',
        feature: null,
        position: 2,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: null,
        value: null,
        feature: null,
        position: 3,
        type: 'SEPARATOR',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Group 2',
        value: null,
        feature: null,
        position: 4,
        type: 'TITLE',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 3',
        value: 'OPTION_3',
        feature: null,
        position: 5,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
      {
        label: 'Option 4',
        value: 'OPTION_4',
        feature: null,
        position: 6,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [],
        action: fn(),
      },
    ],
  },
  argTypes: {
    direction: { control: false },
    selected: { control: false },
  },
}

export const FourOptionsListInGroups: Story = {
  args: {
    options: [
      {
        label: 'Group 1',
        value: 'GROUP_1',
        feature: null,
        position: 0,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [
          {
            label: 'Option 1',
            value: 'OPTION_A_1',
            feature: null,
            position: 0,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
          {
            label: 'Option 2',
            value: 'OPTION_A_2',
            feature: null,
            position: 0,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
          {
            label: 'Option 3',
            value: 'OPTION_A_3',
            feature: null,
            position: 0,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
          {
            label: 'Option 4',
            value: 'OPTION_A_4',
            feature: null,
            position: 0,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
        ],
        action: fn(),
      },
      {
        label: 'Group 2',
        value: 'GROUP_2',
        feature: null,
        position: 1,
        type: 'OPTION',
        isActive: true,
        isBlocked: false,
        isNew: false,
        children: [
          {
            label: 'Option 1',
            value: 'OPTION_B_1',
            feature: null,
            position: 1,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
          {
            label: 'Option 2',
            value: 'OPTION_B_2',
            feature: null,
            position: 1,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
          {
            label: 'Option 3',
            value: 'OPTION_B_3',
            feature: null,
            position: 1,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
          {
            label: 'Option 4',
            value: 'OPTION_B_4',
            feature: null,
            position: 1,
            type: 'OPTION',
            isActive: true,
            isBlocked: false,
            isNew: false,
            children: [],
            action: fn(),
          },
        ],
        action: fn(),
      },
    ],
  },
  argTypes: {
    direction: { control: false },
    selected: { control: false },
  },
}