import type { Meta, StoryObj } from '@storybook/react'
import { Icon } from '../../components/assets/icon/Icon'
import { IconList } from '../../types/icon.types'

const icons: Array<IconList> = [
  'adjust',
  'angle',
  'alert',
  'arrow-left-right',
  'up-down',
  'auto-layout-horizontal',
  'auto-layout-vertical',
  'back',
  'blend-empty',
  'blend',
  'break',
  'caret-down',
  'caret-left',
  'caret-right',
  'caret-up',
  'check',
  'close',
  'component',
  'corner-radius',
  'corners',
  'distribute-horizontal-spacing',
  'distribute-vertical-spacing',
  'draft',
  'effects',
  'ellipses',
  'eyedropper',
  'filter',
  'forward',
  'frame',
  'group',
  'hidden',
  'horizontal-padding',
  'hyperlink',
  'image',
  'instance',
  'key',
  'layout-align-bottom',
  'align-horizontal-centers',
  'align-left',
  'align-right',
  'align-top',
  'align-vertical-centers',
  'layout-grid-columns',
  'layout-grid-rows',
  'layout-grid-uniform',
  'library',
  'link-broken',
  'link-connected',
  'list-detailed',
  'list-tile',
  'list',
  'lock-off',
  'lock-on',
  'minus',
  'play',
  'plus',
  'random',
  'recent',
  'resize-to-fit',
  'resolve-filled',
  'reverse',
  'search-large',
  'search',
  'settings',
  'share',
  'smiley',
  'sort-alpha-asc',
  'sort-alpha-dsc',
  'sort-top-bottom',
  'spacing',
  'star-off',
  'tar-on',
  'stroke-weight',
  'styles',
  'swap',
  'theme',
  'tidy-up-grid',
  'tidy-up-list-horizontal',
  'tidy-up-list-vertical',
  'timer',
  'trash',
  'vertical-padding',
  'visible',
  'warning-large',
  'warning',
  'repository',
  'ellipsis',
  'info',
  'resize-grip',
  'caret',
  'spinner',
  'user',
  'target',
]

const meta = {
  title: 'Example/Assets/Icon',
  component: Icon,
  parameters: {
    layout: 'centered',
  },
  argTypes: {
    iconColor: { control: 'color' },
  },
} satisfies Meta<typeof Icon>

export default meta
type Story = StoryObj<typeof meta>

export const Pictogram: Story = {
  args: {
    type: 'PICTO',
    iconName: 'adjust',
    iconLetter: undefined,
    iconColor: 'var(--figma-color-icon)',
  },
  argTypes: {
    type: { control: false },
    iconName: { control: 'select', options: icons },
    iconLetter: { control: false },
  },
}

export const Letter: Story = {
  args: {
    type: 'LETTER',
    iconName: undefined,
    iconLetter: 'L',
    iconColor: 'var(--figma-color-icon)',
  },
  argTypes: {
    type: { control: false },
    iconName: { control: false },
  },
}
