name: Publish a new version on npm

on:
  push:
    branches:
      - main

jobs:
  npm:
    name: Test, Build and Publish on npm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build module
      run: npm run build

    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.9
      with:
        create_tag: "false"
        commit_pattern: "^Release (\\S+)"
        workspace: "."
        publish_command: "npm"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
